USE RETAILDB;
-- DATA PREPARATION AND UNDERSTANDING
--1. What is the total number of rows in each of the three tables in the database?
SELECT 'Customer' AS TABLE_NAME,COUNT(*) AS TOTAL_ROWS FROM Customer
UNION ALL
SELECT 'Prod_cat_info' AS TABLE_NAME,COUNT(*) AS TOTAL_ROWS FROM prod_cat_info
UNION ALL
SELECT 'Transactions' AS TABLE_NAME,COUNT(*) AS TOTAL_ROWS FROM Transactions

--2. What is the total number of transactions that have a return?
SELECT COUNT(*) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS AS T
WHERE T.Qty<0

--3. As you would have noticed, the dates provided across the datasets are not in a correct format.
--AS first step, please convert the date variables into valid date formats before preceeding ahead.
SELECT FORMAT(CONVERT(DATE,DOB,103),'dd-MM-yyyy') FROM Customer
SELECT FORMAT(CONVERT(DATE,tran_date,103),'dd-MM-yyyy') FROM Transactions

-- Q4. What is the time range of the transaction data available for analysis? Show the output in 
--number of days, months, years simultaneously in different columns.
SELECT MIN(T.tran_date) AS START_DATE, MAX(T.tran_date)END_DATE,
DATEDIFF(DAY,MIN(T.tran_date),MAX(T.tran_date)) AS TOTAL_DAYS,
DATEDIFF(MONTH,MIN(T.tran_date),MAX(T.tran_date)) AS TOTAL_MONTHS,
DATEDIFF(YEAR,MIN(T.tran_date),MAX(T.tran_date)) AS TOTAL_YEARS
FROM Transactions AS T

--Q5. Which product category does the sub-category "DIY" belongs to?
SELECT P.prod_cat
FROM prod_cat_info AS P
WHERE P.prod_subcat = 'DIY'

-- DATA ANALYSIS
--1. Which channel is most frequently used for transactions?
SELECT TOP 1 T.Store_type
FROM Transactions AS T
GROUP BY T.Store_type
ORDER BY COUNT(*) DESC

--2. What is the count of male and female customers in the database?
SELECT C.Gender,COUNT(*) AS TOTAL_CUSTOMERS
FROM Customer AS C
WHERE C.GENDER IS NOT NULL
GROUP BY C.Gender

--3. From which city do we have the maximum number of customers and how many?
SELECT TOP 1 C.city_code, COUNT(*) AS TOTAL_CUSTOMERS 
FROM Customer AS C
GROUP BY C.city_code
ORDER BY TOTAL_CUSTOMERS DESC;

--4. How many sub-categories are there under the Books category?
SELECT P.prod_cat,count(P.prod_subcat) AS NO_OF_SUB_CATEGORIES
FROM prod_cat_info AS P
WHERE P.prod_cat = 'Books'
GROUP BY P.prod_cat

--5. What is the maximum quantity of products ever ordered?
SELECT (MAX(T.Qty)) AS MAXIMUM_QTY
FROM Transactions AS T

--6. What is the net total revenue generated in categories Electronics and Books
SELECT T.prod_cat_code,SUM(T.total_amt) AS TOTAL_REVENUE
FROM Transactions AS T
WHERE T.prod_cat_code IN (SELECT DISTINCT p.prod_cat_code
						  FROM prod_cat_info AS P
						  WHERE P.prod_cat IN ('Electronics','Books'))
GROUP BY T.prod_cat_code

--7. How many customers have >10 transactions with us, excluding returns?
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM(SELECT T.cust_id,COUNT(T.transaction_id) AS TOTAL_TRANSACTIONS
	 FROM Transactions AS T
	 WHERE T.Qty > 0
	 GROUP BY T.cust_id
	 HAVING COUNT(T.transaction_id) > 10
) AS A

--8. What is the combined revenue earned from the Electronics and Clothing categories,
--from Flagship Stores
SELECT SUM(t.total_amt) AS TOTAL_REVENUE
FROM Transactions AS T
WHERE T.prod_cat_code IN(SELECT DISTINCT p.prod_cat_code
						 FROM prod_cat_info AS P
						 WHERE P.prod_cat IN ('Electronics','Clothing'))
						 AND T.Store_type = 'Flagship store'

--9. What is the total revenue generated from Male customers in Electronics category?
--Output should display total revenue by prod sub-cat.
SELECT P.prod_subcat, SUM(T.total_amt) AS TOTAL_REVENUE
FROM Transactions AS T
INNER JOIN prod_cat_info AS P
ON T.prod_cat_code = P.prod_cat_code
AND T.prod_subcat_code = P.prod_sub_cat_code
WHERE T.cust_id IN (SELECT C.customer_Id FROM Customer AS C
					WHERE C.Gender = 'M')
AND P.prod_cat = 'Electronics'
GROUP BY P.prod_subcat

--10. What is the percentage of sales and returns by product sub category; display only top
-- 5 sub categories in terms of sales.
SELECT TOP 5 P.prod_subcat AS SUB_CATEGORY,
	(SUM(T.total_amt)*100/(SELECT SUM(total_amt) FROM Transactions)) AS PERCENTAGE_SALES,
	(SUM(T.Qty)*100/(SELECT SUM(Qty) FROM Transactions)) AS PERCENTAGE_RETURNS
FROM Transactions AS T
INNER JOIN prod_cat_info AS P
ON T.prod_cat_code = P.prod_cat_code
AND T.prod_subcat_code = P.prod_sub_cat_code
GROUP BY P.prod_subcat
ORDER BY SUM(T.total_amt) DESC;

--11. For all customers aged between 25 to 35 years find what is the net total revenue generated by these customers
--in last 30 days of transactions from max transaction date available in the data
SELECT T.cust_id, SUM(T.total_amt) AS TOTAL_REVENUE 
FROM Transactions AS T
WHERE T.cust_id IN (SELECT C.customer_Id FROM Customer AS C
					WHERE DATEDIFF(YEAR,CONVERT(DATE,C.DOB,103),GETDATE()) BETWEEN 25 AND 35)
					AND (CONVERT(DATE,T.tran_date,103) BETWEEN 
						(SELECT DATEADD(DAY,-30,MAX(CONVERT(DATE,T.tran_date,103))) FROM Transactions AS T) 
					AND (SELECT MAX(CONVERT(DATE,T.tran_date,103)) FROM Transactions AS T))
GROUP BY T.cust_id

--12. Which product category has seen the max value of returns in the last 3 months of transactions?
 SELECT TOP 1 T.prod_cat_code, P.prod_cat,SUM(T.total_amt) AS TOTAL_RETURN_VALUE
 FROM Transactions AS T 
 INNER JOIN prod_cat_info AS P
 ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
 WHERE T.QTY < 0 
 AND CONVERT(DATE,T.tran_date,103) BETWEEN 
	(SELECT DATEADD(MONTH,-3,MAX(CONVERT(DATE,T.tran_date,103))) FROM Transactions AS T)
	AND (SELECT MAX(CONVERT(DATE,T.tran_date,103)) FROM Transactions AS T)
 GROUP BY T.prod_cat_code, P.prod_cat
 ORDER BY TOTAL_RETURN_VALUE DESC

 --13. Which store-type sells the maximum products; by value of sales amount and by quantity sold?
 SELECT TOP 1 T.Store_type, SUM(T.total_amt) AS SALES_AMT, SUM(T.Qty) AS TOTAL_QTY 
 FROM Transactions AS T
 GROUP BY T.Store_type
 ORDER BY SALES_AMT DESC, TOTAL_QTY DESC

 --14. What are the categories for which average revenue is above overall average.
 SELECT T.prod_cat_code, P.prod_cat ,AVG(T.total_amt) AS AVG_REVENUE
 FROM Transactions AS T
 INNER JOIN prod_cat_info AS P
 ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
 GROUP BY T.prod_cat_code, P.prod_cat
 HAVING AVG(T.total_amt) > (SELECT AVG(T.total_amt) FROM Transactions AS T)

 --15. Find the average and total revenue by each sub-category for the categories which are among top 5 
 --categories in terms of quantity sold.
 SELECT T.prod_subcat_code,P.prod_subcat ,AVG(T.total_amt) AS AVG_REVENUE, SUM(T.total_amt) AS TOTAL_REVENUE
 FROM Transactions AS T
 INNER JOIN prod_cat_info AS P
 ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
 WHERE T.prod_cat_code IN (	SELECT TOP 5 T.prod_cat_code FROM Transactions AS T
							GROUP BY T.prod_cat_code
							ORDER BY SUM(T.Qty) DESC)
GROUP BY T.prod_subcat_code,P.prod_subcat 

